@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant frontend

box backend #LightGray
frontend -> leads_ms: POST /v1/leads

activate leads_ms

alt validate request
leads_ms -> leads_ms
    note left
        <size:10>**Request body:**</size>
        <size:10>{</size>
        <size:10>   "firstname": "John",</size>
        <size:10>   "phoneNumber": "99999999999",</size>
        <size:10>   "email": "John@email.com"</size>
        <size:10>   "lastname": "Doe"</size>
        <size:10>}</size>
    end note
else if request is valid
database leads_ms_db

leads_ms -> leads_ms_db: create lead
activate leads_ms_db

leads_ms_db --> leads_ms: return lead
deactivate leads_ms_db
leads_ms --> frontend: Return Http Status **200** and response with UUID

else if request is invalid
leads_ms --> frontend: Return Http Status **422** with exception error

deactivate leads_ms
end box
end

@enduml