@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant frontend

box backend #LightGray
frontend -> leads_ms: PUT /v1/leads

activate leads_ms
database leads_ms_db

alt validate request
leads_ms -> leads_ms: Validate request body

leads_ms -> leads_ms_db: Verify if Lead with phone exists
activate leads_ms_db
leads_ms_db --> leads_ms: If return lead, phone number exists.\n If not, phone number not exists in database.

    note left
        <size:10>**Request body:**</size>
        <size:10>{</size>
        <size:10>   "firstname": "John",</size>
        <size:10>   "phone": "99999999999",</size>
        <size:10>   "email": "John@email.com"</size>
        <size:10>   "lastname": "Doe"</size>
        <size:10>}</size>
    end note
else If lead phone number exists

leads_ms -> leads_ms_db: updated lead

leads_ms_db --> leads_ms: return lead updated
deactivate leads_ms_db
leads_ms --> frontend: Return Http Status **200**\n and response lead with fields updated

else If lead phone number not exists
leads_ms --> frontend: Return Http Status **422**\n with exception error

deactivate leads_ms
end box
end

@enduml